version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 2000
  enableJavaScript: false
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 700
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false